global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
- /etc/prometheus/alerts.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
- job_name: go-auth
  dns_sd_configs:
  - names:
    - tasks.go-auth
    type: A
    port: 80
  metric_relabel_configs:
  - source_labels:
    - path
    target_label: route
    regex: (.+)
  - source_labels:
    - status_code
    target_label: status
    regex: (.+)
  - action: labeldrop
    regex: path|status_code
- job_name: authd
  dns_sd_configs:
  - names:
    - tasks.authd
    type: A
    port: 8080
- job_name: nginx
  dns_sd_configs:
  - names:
    - tasks.nginx-exporter
    type: A
    port: 9113
- job_name: nginxlog
  dns_sd_configs:
  - names:
    - tasks.nginxlog-exporter
    type: A
    port: 4040
- job_name: postgres
  dns_sd_configs:
  - names:
    - tasks.postgres-exporter
    type: A
    port: 9187
- job_name: auth-postgres
  dns_sd_configs:
  - names:
    - tasks.auth-postgres-exporter
    type: A
    port: 9187
- job_name: redis
  dns_sd_configs:
  - names:
    - tasks.redis-exporter
    type: A
    port: 9121
- job_name: node
  dns_sd_configs:
  - names:
    - tasks.node-exporter
    type: A
    port: 9100
- job_name: prometheus-self
  dns_sd_configs:
  - names:
    - tasks.prometheus
    type: A
    port: 9090
- job_name: alertmanager
  dns_sd_configs:
  - names:
    - tasks.alertmanager
    type: A
    port: 9093
- job_name: http-probe
  metrics_path: /probe
  params:
    module:
    - http_2xx
  static_configs:
  - targets:
    - http://go-auth:80/ping
    - http://authd:8080/healthz
    - http://nginx:8080/nginx-health
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115
- job_name: blackbox
  dns_sd_configs:
  - names:
    - tasks.blackbox-exporter
    type: A
    port: 9115
