FROM golang:1.25-alpine

WORKDIR /usr/src/app

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV ENV_TYPE=TEST

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN chmod +x scripts/test.sh

CMD ["./scripts/test.sh"]
