FROM golang:alpine AS compiler

WORKDIR /usr/src/app

ENV CGO_ENABLED=0
ENV GOOS=linux

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . ./
ENV ENV_TYPE=TEST
ARG VAR=1
RUN chmod +x scripts/test.sh && ./scripts/test.sh
