FROM golang:1.25-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends poppler-utils librdkit-dev libboost-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

ENV CGO_ENABLED=1
ENV GO_TEST_TAGS=rdkit
ENV GOOS=linux
ENV ENV_TYPE=TEST

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN chmod +x scripts/test.sh

CMD ["./scripts/test.sh"]
