limit_conn_zone $binary_remote_addr zone=addr:10m;
limit_req_zone $binary_remote_addr zone=one:10m rate=20r/s;

upstream backend {
    server go-auth:80;
}

upstream grafana {
    server grafana:3000;
}

server {
    listen 8080;
    server_name _;

    location /nginx-health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        deny all;
    }
}

server {
    server_name 176.108.251.108.nip.io;
    limit_conn addr 8;
    client_max_body_size 10M;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_redirect off;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/176.108.251.108.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/176.108.251.108.nip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    server_name 176.108.251.108.sslip.io;
    limit_conn addr 8;
    client_max_body_size 6M;

    location / {
        proxy_pass http://grafana;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_redirect off;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/176.108.251.108.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/176.108.251.108.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = 176.108.251.108.nip.io) {
        return 301 https://$host$request_uri;
    }

    server_name 176.108.251.108.nip.io;
    listen 80;
    return 404;
}

server {
    if ($host = 176.108.251.108.sslip.io) {
        return 301 https://$host$request_uri;
    }

    server_name 176.108.251.108.sslip.io;
    listen 80;
    return 404;
}
